import time
import unittest
import warnings
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains

class TestInsertarUsuarioValidaciones(unittest.TestCase):
    def setUp(self):
        options = webdriver.ChromeOptions() 
        options.add_argument("start-maximized")
        options.add_experimental_option('excludeSwitches', ['enable-logging'])
        self.driver = webdriver.Chrome(options=options)
        
    def test_insertarUsuarioValidaciones(self):
        driver = self.driver
        driver.get("http://localhost:3000/")
        driver.find_element(By.CSS_SELECTOR, ".correo-ancho").send_keys("diego.damian@pucp.edu.pe")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".contrasenia-input").send_keys("1234abcd")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".iniciar-sesion-btn").click()
        time.sleep(1)
        driver.execute_script("window.scrollTo(0,0)")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".listaRoles:nth-child(1)").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".btnAniadirGC > button").click()
        time.sleep(1)
        driver.find_element(By.NAME, "nombres").click()
        time.sleep(1)
        driver.find_element(By.NAME, "nombres").send_keys("Usuario1")
        time.sleep(1)
        driver.find_element(By.NAME, "apPaterno").click()
        time.sleep(1)
        driver.find_element(By.NAME, "apPaterno").send_keys("ApellidoPat")
        time.sleep(1)
        driver.find_element(By.NAME, "codigoPUCP").click()
        time.sleep(1)
        driver.find_element(By.NAME, "codigoPUCP").send_keys("5432978")
        time.sleep(1)
        driver.find_element(By.ID, "celular").click()
        time.sleep(1)
        driver.find_element(By.ID, "celular").send_keys("25348974")
        time.sleep(1)
        driver.find_element(By.ID, "apMaterno").click()
        time.sleep(1)
        driver.find_element(By.ID, "apMaterno").send_keys("Apmat")
        time.sleep(1)
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        element = self.driver.find_element(By.NAME, "correo")
        time.sleep(1)
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        element = self.driver.find_element(By.NAME, "correo")
        time.sleep(1)
        actions = ActionChains(self.driver)
        time.sleep(1)
        actions.double_click(element).perform()
        time.sleep(1)
        driver.find_element(By.NAME, "correo").click()
        time.sleep(1)
        driver.find_element(By.NAME, "correo").send_keys("correoprueba243@pucp.ed.pe")
        time.sleep(1)
        driver.find_element(By.ID, "correoSecundario").click()
        time.sleep(1)
        driver.find_element(By.ID, "correoSecundario").send_keys("correoprueba243@pucp.ed.pe")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".contenedorAC:nth-child(4)").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".btnEditarAC").click()
        time.sleep(1)
        driver.find_element(By.NAME, "codigoPUCP").click()
        time.sleep(1)
        driver.find_element(By.NAME, "codigoPUCP").send_keys("54329738")
        time.sleep(1)
        driver.find_element(By.ID, "celular").click()
        time.sleep(1)
        driver.find_element(By.ID, "celular").send_keys("2534897423")
        time.sleep(1)
        driver.find_element(By.NAME, "nombres").click()
        time.sleep(1)
        driver.find_element(By.NAME, "nombres").send_keys("Usuario")
        time.sleep(1)
        driver.find_element(By.ID, "celular").click()
        time.sleep(1)
        driver.find_element(By.ID, "celular").send_keys("253489742")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".btnEditarAC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".botonAceptarAC").click()
        time.sleep(1)
        
    def tearDown(self):
        warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)
        self.driver.close()
        print("Test completado")
        
if __name__ == "__main__":
    unittest.main()