# Generated by Selenium IDE
import time
import json
import unittest
import warnings
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAdministradorGestionarCuentasBuscar:
    def setUp(self):
        options = webdriver.ChromeOptions()
        options.add_argument("start-maximized")
        options.add_experimental_option("excludeSwitches", ["enable-logging"])
        self.driver = webdriver.Chrome(options=options)

    def test_administradorGestionarCuentasBuscar(self):
        driver = self.driver
        driver.get("http://localhost:3000/")
        driver.set_window_size(1552, 840)
        driver.find_element(By.CSS_SELECTOR, ".correo-ancho").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".correo-ancho").send_keys(
            "fernando.vergara@pucp.edu.pe"
        )
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".contrasenia-input").send_keys("tovar")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".iniciar-sesion-btn").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".listaRoles:nth-child(1)").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").send_keys("20185474")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".bi-search").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".area-trabajo-admin").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".bi-search").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").send_keys("Lian")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".bi-search").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.ID, "boton-buscar-gc").click()
        time.sleep(1)
        element = self.driver.find_element(By.ID, "boton-buscar-gc")
        time.sleep(1)
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        time.sleep(1)
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").send_keys("Chero")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".bi-search").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").send_keys("Guzman")
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".bi-search").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, ".form-controlGC").click()
        time.sleep(1)
        driver.find_element(By.ID, "boton-buscar-gc").click()
        time.sleep(1)

    def tearDown(self):
        warnings.filterwarnings(
            action="ignore", message="unclosed", category=ResourceWarning
        )
        self.driver.close()
        print("Test completado")


if __name__ == "__main__":
    unittest.main()
